### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by haakonrp** [lejeffe/MonsterHP#6]
Got this NPE while doing TOA:

```
2022-09-14 18:00:58 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at net.runelite.client.ui.overlay.OverlayUtil.renderTextLocation(OverlayUtil.java:96)
	at com.monsterhp.MonsterHPOverlay.renderTimer(MonsterHPOverlay.java:94)
	at com.monsterhp.MonsterHPOverlay.lambda$render$0(MonsterHPOverlay.java:59)
	at java.base/java.util.HashMap.forEach(Unknown Source)
	at com.monsterhp.MonsterHPOverlay.render(MonsterHPOverlay.java:59)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:719)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:322)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:229)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:444)
	at gp.aj(gp.java:28458)
	at cz.hi(cz.java:4459)
	at bl.ju(bl.java:9883)
	at bl.ju(bl.java:9914)
	at ga.jy(ga.java:9772)
	at client.gh(client.java:4313)
	at client.as(client.java:1117)
	at ai.pp(ai.java:364)
	at ai.run(ai.java:318)
	at java.base/java.lang.Thread.run(Unknown Source)
```

These are my settings:
![image](https://user-images.githubusercontent.com/14054864/190218114-131be69d-8c94-405c-a200-c0ec6bae1f54.png)

**Comment by lejeffe** [comment]
Did the client crash on you? I don't see anything obvious wrong with the code. i'll take a deeper look this weekend. Could you give me a better explanation of the location where this happened?

**Comment by haakonrp** [comment]
No, the client did not crash, so not a big issue. Just randomly checked the logs, and wanted you to know.

Not exactly sure for which boss in TOA this happened, but it might be Akkha or the Wardens when they're changing state which causes `canvasPoint` to be null?

A null check for canvasPoint before calling `OverlayUtil.renderTextLocation` might fix the issue?

**Comment by haakonrp** [comment]
Confimed that this is only happening on Akkha (probably on when transitioning to orb phase).

**Comment by lejeffe** [comment]
I have made a small change that should catch the NPE. Let me know if this still exists after Runelite accepts the update

**Comment by haakonrp** [comment]
Seems like issue is still present.

Got the same exception yesterday:
```
...

2022-09-19 16:03:45 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "monster-hp-percentage" version "1.2" commit "6f19dbd2d9b0ffb5b72395b98382c20e434b68b8"

...

2022-09-19 16:47:04 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at net.runelite.client.ui.overlay.OverlayUtil.renderTextLocation(OverlayUtil.java:96)
	at com.monsterhp.MonsterHPOverlay.renderTimer(MonsterHPOverlay.java:94)
	at com.monsterhp.MonsterHPOverlay.lambda$render$0(MonsterHPOverlay.java:59)
	at java.base/java.util.HashMap.forEach(Unknown Source)
	at com.monsterhp.MonsterHPOverlay.render(MonsterHPOverlay.java:59)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:719)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:322)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:229)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:444)
	at gp.aj(gp.java:28458)
	at cz.hi(cz.java:4459)
	at bl.ju(bl.java:9883)
	at bl.ju(bl.java:9914)
	at ga.jy(ga.java:9772)
	at client.gh(client.java:4313)
	at client.as(client.java:1117)
	at ai.pp(ai.java:364)
	at ai.run(ai.java:318)
	at java.base/java.lang.Thread.run(Unknown Source)

...

2022-09-19 22:06:54 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2022-09-19 22:06:54 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
```
Full log:
[client_2022-09-19.0.log](https://github.com/lejeffe/MonsterHP/files/9611220/client_2022-09-19.0.log)

**Comment by haakonrp** [comment]
This only occurs when warden is transitioning from P2 -> P3. 
Did not occur on Akkha as stated previously.
